[package]
name = "agora-mls"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
shellexpand = "3.1.1"
uuid = { version = "1.18.1", features = ["v4"] }
